services:
  db:
    container_name: db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: discord
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U admin -d discord']
      interval: 5s
      timeout: 5s
      retries: 10

  migrate:
    container_name: migrate
    build:
      context: .
      dockerfile: Dockerfile.migrate
    env_file: .env
    depends_on:
      db:
        condition: service_healthy