global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'core-microservices'
    metrics_path: /metrics
    static_configs:
      - targets: ['core:3002']

  - job_name: 'chat-microservices'
    metrics_path: /metrics
    static_configs:
      - targets: ['chat:3001']

  - job_name: 'server-microservices'
    metrics_path: /metrics
    static_configs:
      - targets: ['server:3003']

  - job_name: 'gateway-microservices'
    metrics_path: /metrics
    static_configs:
      - targets: ['gateway:3000']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    metrics_path: /metrics

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    metrics_path: /metrics

  - job_name: 'rabbitmq'
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'rabbitmq:15692' ]

  - job_name: 'minio-job'
    metrics_path: '/minio/prometheus/metrics'
    static_configs:
      - targets: ['minio:9000']
